### ISSUE TITLE
Error while using Thumbnail Api

### ISSUE THREAD

**Issue by enkosoftware** [kaltura/server#12340]
- [X ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [X ] This is not a support request or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) or submitted to the support team in the form of a ticket 
(i hope so, but the Kaltura Forum Login doesn't work, sso.forum.kaltura.org times out)

## Bug report
We are using the thumbnail api to create thumbnails from a video timestamp (using the vid_sec parameter). Randomly the creation of the thumbnail fails and the server responds with a 404. Then this specific timestamp fails everytime for like 5 to 10 minutes, before it suddenly starts working again and creates the thumbnail. In this time other timestamps on the same entry still work fine.

## Kaltura ENV
Propus-16.14.0

**Relevant errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**
2023-08-30 12:57:47 [0.004729] [92.117.221.74] [1402175021] [1] [PS2] [kInfraMemcacheCacheWrapper::outputStats] NOTICE: instance:127.0.0.1:11211, conn_count:3, conn_time:0.00029873847961426, op_count:5, op_time:0.00050163269042969
2023-08-30 12:57:47 [0.003428] [92.117.221.74] [1402175021] [2] [PS2] [sfContext->initialize] INFO: {sfContext} initialization
2023-08-30 12:57:47 [0.000277] [92.117.221.74] [1402175021] [3] [PS2] [sfController->initialize] INFO: {sfController} initialization
2023-08-30 12:57:47 [0.000228] [92.117.221.74] [1402175021] [4] [PS2] [sfRouting->parse] INFO: {sfRouting} match route [default] "/:module/:action/*"
2023-08-30 12:57:47 [0.000096] [92.117.221.74] [1402175021] [5] [PS2] [sfWebRequest->loadParameters] INFO: {sfRequest} request parameters array (  'module' => 'extwidget',  'action' => 'thumbnail',  'entry_id' => '0_ozvdn3li',  'width' => '0',  'height' => '0',  'src_x' => '0',  'src_y' => '0',  'src_w' => '0',  'src_h' => '0',  'format' => 'png',  'type' => '1',  'vid_sec' => '4.9',)
2023-08-30 12:57:47 [0.000204] [92.117.221.74] [1402175021] [6] [PS2] [sfFrontWebController->dispatch] INFO: {sfController} dispatch request
2023-08-30 12:57:47 [0.000339] [92.117.221.74] [1402175021] [7] [PS2] [sfFilterChain->execute] INFO: {sfFilter} executing filter "sfRenderingFilter"
2023-08-30 12:57:47 [0.000038] [92.117.221.74] [1402175021] [8] [PS2] [sfFilterChain->execute] INFO: {sfFilter} executing filter "myHealthCheckAndSecurityFilter"
2023-08-30 12:57:47 [0.000096] [92.117.221.74] [1402175021] [9] [PS2] [myHealthCheckAndSecurityFilter->basicSecureRequest] WARN: basicSecureRequest: took [3.0994415283203E-6] seconds
2023-08-30 12:57:47 [0.000034] [92.117.221.74] [1402175021] [10] [PS2] [sfFilterChain->execute] INFO: {sfFilter} executing filter "sfCommonFilter"
2023-08-30 12:57:47 [0.000057] [92.117.221.74] [1402175021] [11] [PS2] [sfFilterChain->execute] INFO: {sfFilter} executing filter "sfFlashFilter"
2023-08-30 12:57:47 [0.000086] [92.117.221.74] [1402175021] [12] [PS2] [sfFilterChain->execute] INFO: {sfFilter} executing filter "sfExecutionFilter"
2023-08-30 12:57:47 [0.001452] [92.117.221.74] [1402175021] [13] [PS2] [KalturaPDO->__construct] DEBUG: conn took - 0.00045490264892578 seconds to mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2023-08-30 12:57:47 [0.000116] [92.117.221.74] [1402175021] [14] [PS2] [Propel::initConnection] NOTICE: total conn took 0.00057697296142578 mysql:host=127.0.0.1;port=3306;dbname=kaltura;
2023-08-30 12:57:47 [0.000067] [92.117.221.74] [1402175021] [15] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000297] [92.117.221.74] [1402175021] [16] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT entry.ID, entry.KSHOW_ID, entry.KUSER_ID, entry.NAME, entry.TYPE, entry.MEDIA_TYPE, entry.DATA, entry.THUMBNAIL, entry.VIEWS, entry.VOTES, entry.COMMENTS, entry.FAVORITES, entry.TOTAL_RANK, entry.RANK, entry.TAGS, entry.ANONYMOUS, entry.STATUS, entry.SOURCE, entry.SOURCE_ID, entry.SOURCE_LINK, entry.LICENSE_TYPE, entry.CREDIT, entry.LENGTH_IN_MSECS, entry.CREATED_AT, entry.UPDATED_AT, entry.PARTNER_ID, entry.DISPLAY_IN_SEARCH, entry.SUBP_ID, entry.CUSTOM_DATA, entry.SCREEN_NAME, entry.SITE_URL, entry.PERMISSIONS, entry.GROUP_ID, entry.PLAYS, entry.PARTNER_DATA, entry.INT_ID, entry.INDEXED_CUSTOM_DATA_1, entry.DESCRIPTION, entry.MEDIA_DATE, entry.ADMIN_TAGS, entry.MODERATION_STATUS, entry.MODERATION_COUNT, entry.MODIFIED_AT, entry.PUSER_ID, entry.ACCESS_CONTROL_ID, entry.CONVERSION_PROFILE_ID, entry.CATEGORIES, entry.CATEGORIES_IDS, entry.START_DATE, entry.END_DATE, entry.FLAVOR_PARAMS_IDS, entry.AVAILABLE_FROM, entry.LAST_PLAYED_AT FROM `entry` WHERE entry.ID='0_ozvdn3li'
2023-08-30 12:57:47 [0.000496] [92.117.221.74] [1402175021] [17] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.0004420280456543 seconds
2023-08-30 12:57:47 [0.000537] [92.117.221.74] [1402175021] [18] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000142] [92.117.221.74] [1402175021] [19] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT partner.ID, partner.PARTNER_NAME, partner.PARTNER_ALIAS, partner.URL1, partner.URL2, partner.SECRET, partner.ADMIN_SECRET, partner.MAX_NUMBER_OF_HITS_PER_DAY, partner.APPEAR_IN_SEARCH, partner.DEBUG_LEVEL, partner.CREATED_AT, partner.UPDATED_AT, partner.ANONYMOUS_KUSER_ID, partner.KS_MAX_EXPIRY_IN_SECONDS, partner.CREATE_USER_ON_DEMAND, partner.PREFIX, partner.ADMIN_NAME, partner.ADMIN_EMAIL, partner.DESCRIPTION, partner.COMMERCIAL_USE, partner.MODERATE_CONTENT, partner.NOTIFY, partner.CUSTOM_DATA, partner.SERVICE_CONFIG_ID, partner.STATUS, partner.CONTENT_CATEGORIES, partner.TYPE, partner.PHONE, partner.DESCRIBE_YOURSELF, partner.ADULT_CONTENT, partner.PARTNER_PACKAGE, partner.USAGE_PERCENT, partner.STORAGE_USAGE, partner.EIGHTY_PERCENT_WARNING, partner.USAGE_LIMIT_WARNING, partner.MONITOR_USAGE, partner.PRIORITY_GROUP_ID, partner.PARTNER_GROUP_TYPE, partner.PARTNER_PARENT_ID, partner.KMC_VERSION FROM `partner` WHERE partner.ID IS NULL
2023-08-30 12:57:47 [0.000235] [92.117.221.74] [1402175021] [20] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00019288063049316 seconds
2023-08-30 12:57:47 [0.000154] [92.117.221.74] [1402175021] [21] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000119] [92.117.221.74] [1402175021] [22] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT partner.ID, partner.PARTNER_NAME, partner.PARTNER_ALIAS, partner.URL1, partner.URL2, partner.SECRET, partner.ADMIN_SECRET, partner.MAX_NUMBER_OF_HITS_PER_DAY, partner.APPEAR_IN_SEARCH, partner.DEBUG_LEVEL, partner.CREATED_AT, partner.UPDATED_AT, partner.ANONYMOUS_KUSER_ID, partner.KS_MAX_EXPIRY_IN_SECONDS, partner.CREATE_USER_ON_DEMAND, partner.PREFIX, partner.ADMIN_NAME, partner.ADMIN_EMAIL, partner.DESCRIPTION, partner.COMMERCIAL_USE, partner.MODERATE_CONTENT, partner.NOTIFY, partner.CUSTOM_DATA, partner.SERVICE_CONFIG_ID, partner.STATUS, partner.CONTENT_CATEGORIES, partner.TYPE, partner.PHONE, partner.DESCRIBE_YOURSELF, partner.ADULT_CONTENT, partner.PARTNER_PACKAGE, partner.USAGE_PERCENT, partner.STORAGE_USAGE, partner.EIGHTY_PERCENT_WARNING, partner.USAGE_LIMIT_WARNING, partner.MONITOR_USAGE, partner.PRIORITY_GROUP_ID, partner.PARTNER_GROUP_TYPE, partner.PARTNER_PARENT_ID, partner.KMC_VERSION FROM `partner` WHERE partner.ID='100'
2023-08-30 12:57:47 [0.000270] [92.117.221.74] [1402175021] [23] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00022196769714355 seconds
2023-08-30 12:57:47 [0.000530] [92.117.221.74] [1402175021] [24] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000153] [92.117.221.74] [1402175021] [25] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT access_control.ID, access_control.PARTNER_ID, access_control.NAME, access_control.SYSTEM_NAME, access_control.DESCRIPTION, access_control.CREATED_AT, access_control.UPDATED_AT, access_control.DELETED_AT, access_control.SITE_RESTRICT_TYPE, access_control.SITE_RESTRICT_LIST, access_control.COUNTRY_RESTRICT_TYPE, access_control.COUNTRY_RESTRICT_LIST, access_control.KS_RESTRICT_PRIVILEGE, access_control.PRV_RESTRICT_PRIVILEGE, access_control.PRV_RESTRICT_LENGTH, access_control.KDIR_RESTRICT_TYPE, access_control.CUSTOM_DATA, access_control.RULES FROM `access_control` WHERE access_control.ID IS NULL  AND access_control.DELETED_AT IS NULL
2023-08-30 12:57:47 [0.000195] [92.117.221.74] [1402175021] [26] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00013899803161621 seconds
2023-08-30 12:57:47 [0.000171] [92.117.221.74] [1402175021] [27] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000097] [92.117.221.74] [1402175021] [28] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT access_control.ID, access_control.PARTNER_ID, access_control.NAME, access_control.SYSTEM_NAME, access_control.DESCRIPTION, access_control.CREATED_AT, access_control.UPDATED_AT, access_control.DELETED_AT, access_control.SITE_RESTRICT_TYPE, access_control.SITE_RESTRICT_LIST, access_control.COUNTRY_RESTRICT_TYPE, access_control.COUNTRY_RESTRICT_LIST, access_control.KS_RESTRICT_PRIVILEGE, access_control.PRV_RESTRICT_PRIVILEGE, access_control.PRV_RESTRICT_LENGTH, access_control.KDIR_RESTRICT_TYPE, access_control.CUSTOM_DATA, access_control.RULES FROM `access_control` WHERE access_control.ID IS NULL  AND access_control.DELETED_AT IS NULL
2023-08-30 12:57:47 [0.000129] [92.117.221.74] [1402175021] [29] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 9.2029571533203E-5 seconds
2023-08-30 12:57:47 [0.000269] [92.117.221.74] [1402175021] [30] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000127] [92.117.221.74] [1402175021] [31] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT permission.ID, permission.TYPE, permission.NAME, permission.FRIENDLY_NAME, permission.DESCRIPTION, permission.PARTNER_ID, permission.STATUS, permission.DEPENDS_ON_PERMISSION_NAMES, permission.TAGS, permission.CREATED_AT, permission.UPDATED_AT, permission.CUSTOM_DATA FROM `permission` WHERE permission.PARTNER_ID IN ('100','0') AND permission.NAME='FEATURE_BLOCK_THUMBNAIL_CAPTURE' ORDER BY permission.STATUS ASC LIMIT 1
2023-08-30 12:57:47 [0.000309] [92.117.221.74] [1402175021] [32] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00026702880859375 seconds
2023-08-30 12:57:47 [0.000346] [92.117.221.74] [1402175021] [33] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] DEBUG: key [object_type:[1], object_id:[0_ozvdn3li], version:[100002], object_sub_type[3], partner_id[100]], fetch_from_remote_if_no_local [1], strict []
2023-08-30 12:57:47 [0.002721] [92.117.221.74] [1402175021] [34] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000181] [92.117.221.74] [1402175021] [35] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT file_sync.ID, file_sync.PARTNER_ID, file_sync.OBJECT_TYPE, file_sync.OBJECT_ID, file_sync.VERSION, file_sync.OBJECT_SUB_TYPE, file_sync.DC, file_sync.ORIGINAL, file_sync.CREATED_AT, file_sync.UPDATED_AT, file_sync.READY_AT, file_sync.SYNC_TIME, file_sync.STATUS, file_sync.FILE_TYPE, file_sync.LINKED_ID, file_sync.LINK_COUNT, file_sync.FILE_ROOT, file_sync.FILE_PATH, file_sync.FILE_SIZE, file_sync.CUSTOM_DATA, file_sync.DELETED_ID FROM `file_sync` WHERE file_sync.OBJECT_ID='0_ozvdn3li' AND file_sync.OBJECT_TYPE='1' AND file_sync.OBJECT_SUB_TYPE='3' AND file_sync.VERSION='100002' AND (file_sync.STATUS='2' AND file_sync.STATUS NOT IN ('3','4')) ORDER BY file_sync.DC ASC
2023-08-30 12:57:47 [0.000388] [92.117.221.74] [1402175021] [36] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00031495094299316 seconds
2023-08-30 12:57:47 [0.003938] [92.117.221.74] [1402175021] [37] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000168] [92.117.221.74] [1402175021] [38] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT file_sync.ID, file_sync.PARTNER_ID, file_sync.OBJECT_TYPE, file_sync.OBJECT_ID, file_sync.VERSION, file_sync.OBJECT_SUB_TYPE, file_sync.DC, file_sync.ORIGINAL, file_sync.CREATED_AT, file_sync.UPDATED_AT, file_sync.READY_AT, file_sync.SYNC_TIME, file_sync.STATUS, file_sync.FILE_TYPE, file_sync.LINKED_ID, file_sync.LINK_COUNT, file_sync.FILE_ROOT, file_sync.FILE_PATH, file_sync.FILE_SIZE, file_sync.CUSTOM_DATA, file_sync.DELETED_ID FROM `file_sync` WHERE file_sync.ID='11245' AND file_sync.STATUS NOT IN ('3','4')
2023-08-30 12:57:47 [0.000275] [92.117.221.74] [1402175021] [39] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00023221969604492 seconds
2023-08-30 12:57:47 [0.000112] [92.117.221.74] [1402175021] [40] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync was found locally
2023-08-30 12:57:47 [0.000029] [92.117.221.74] [1402175021] [41] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync DC: 0
2023-08-30 12:57:47 [0.004674] [92.117.221.74] [1402175021] [42] [PS2] [myEntryUtils::resizeEntryImage] DEBUG: Path for saving thumbnail is [/opt/kaltura/web//content/entry/tempthumb/0/2/0_ozvdn3li_0_0_1__ffffff_0_0_0_0_0_4.9_-1_-1_2_100002.png]
2023-08-30 12:57:47 [0.000844] [92.117.221.74] [1402175021] [43] [PS2] [myEntryUtils::resizeEntryImage] DEBUG: Final path not found [/opt/kaltura/web//content/entry/tempthumb/0/2/0_ozvdn3li_0_0_1__ffffff_0_0_0_0_0_4.9_-1_-1_2_100002.png], checking if file exists on old mount path [/opt/kaltura/web//content/entry/tempthumb/0/2/0_ozvdn3li_0_0_1__ffffff_0_0_0_0_0_4.9_-1_-1_2_100002.jpg]
2023-08-30 12:57:47 [0.001782] [92.117.221.74] [1402175021] [44] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] DEBUG: key [object_type:[1], object_id:[0_ozvdn3li], version:[100002], object_sub_type[3], partner_id[100]], fetch_from_remote_if_no_local [], strict []
2023-08-30 12:57:47 [0.001805] [92.117.221.74] [1402175021] [45] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000238] [92.117.221.74] [1402175021] [46] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT file_sync.ID, file_sync.PARTNER_ID, file_sync.OBJECT_TYPE, file_sync.OBJECT_ID, file_sync.VERSION, file_sync.OBJECT_SUB_TYPE, file_sync.DC, file_sync.ORIGINAL, file_sync.CREATED_AT, file_sync.UPDATED_AT, file_sync.READY_AT, file_sync.SYNC_TIME, file_sync.STATUS, file_sync.FILE_TYPE, file_sync.LINKED_ID, file_sync.LINK_COUNT, file_sync.FILE_ROOT, file_sync.FILE_PATH, file_sync.FILE_SIZE, file_sync.CUSTOM_DATA, file_sync.DELETED_ID FROM `file_sync` WHERE file_sync.OBJECT_ID='0_ozvdn3li' AND file_sync.OBJECT_TYPE='1' AND file_sync.OBJECT_SUB_TYPE='3' AND file_sync.VERSION='100002' AND file_sync.DC IN ('0') AND (file_sync.STATUS='2' AND file_sync.STATUS NOT IN ('3','4')) ORDER BY file_sync.DC ASC
2023-08-30 12:57:47 [0.000530] [92.117.221.74] [1402175021] [47] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00048494338989258 seconds
2023-08-30 12:57:47 [0.003480] [92.117.221.74] [1402175021] [48] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync was found locally
2023-08-30 12:57:47 [0.000041] [92.117.221.74] [1402175021] [49] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync DC: 0
2023-08-30 12:57:47 [0.000142] [92.117.221.74] [1402175021] [50] [PS2] [kFileSyncUtils::getReadyLocalFilePathForKey] DEBUG: key [object_type:[1], object_id:[0_ozvdn3li], version:[100002], object_sub_type[3], partner_id[100]], strict []
2023-08-30 12:57:47 [0.000030] [92.117.221.74] [1402175021] [51] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] DEBUG: key [object_type:[1], object_id:[0_ozvdn3li], version:[100002], object_sub_type[3], partner_id[100]], fetch_from_remote_if_no_local [], strict []
2023-08-30 12:57:47 [0.004295] [92.117.221.74] [1402175021] [52] [PS2] [DbManager::connectFallbackLogic] DEBUG: connected to propel3
2023-08-30 12:57:47 [0.000255] [92.117.221.74] [1402175021] [53] [PS2] [KalturaStatement->execute] DEBUG: /* kaltura[1402175021][propel3] */ SELECT file_sync.ID, file_sync.PARTNER_ID, file_sync.OBJECT_TYPE, file_sync.OBJECT_ID, file_sync.VERSION, file_sync.OBJECT_SUB_TYPE, file_sync.DC, file_sync.ORIGINAL, file_sync.CREATED_AT, file_sync.UPDATED_AT, file_sync.READY_AT, file_sync.SYNC_TIME, file_sync.STATUS, file_sync.FILE_TYPE, file_sync.LINKED_ID, file_sync.LINK_COUNT, file_sync.FILE_ROOT, file_sync.FILE_PATH, file_sync.FILE_SIZE, file_sync.CUSTOM_DATA, file_sync.DELETED_ID FROM `file_sync` WHERE file_sync.OBJECT_ID='0_ozvdn3li' AND file_sync.OBJECT_TYPE='1' AND file_sync.OBJECT_SUB_TYPE='3' AND file_sync.VERSION='100002' AND file_sync.DC IN ('0') AND (file_sync.STATUS='2' AND file_sync.STATUS NOT IN ('3','4')) ORDER BY file_sync.DC ASC
2023-08-30 12:57:47 [0.000587] [92.117.221.74] [1402175021] [54] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00052690505981445 seconds
2023-08-30 12:57:47 [0.003355] [92.117.221.74] [1402175021] [55] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync was found locally
2023-08-30 12:57:47 [0.000038] [92.117.221.74] [1402175021] [56] [PS2] [kFileSyncUtils::getReadyFileSyncForKey] INFO: FileSync DC: 0
2023-08-30 12:57:47 [0.000797] [92.117.221.74] [1402175021] [57] [PS2] [kFileSyncUtils::getReadyLocalFilePathForKey] INFO: path [/opt/kaltura/web//content/entry/data/0/2/0_ozvdn3li_0_91sgolnt_12.jpg]
2023-08-30 12:57:47 [0.000939] [92.117.221.74] [1402175021] [58] [PS2] [KExternalErrors::dieError] ERR: Exception: exiting on error 11 - processing capture thumbnail in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(147): KalturaLog::err('exiting on erro...')
#1 /opt/kaltura/app/alpha/apps/kaltura/lib/myEntryUtils.class.php(852): KExternalErrors::dieError(11)
#2 /opt/kaltura/app/alpha/apps/kaltura/modules/extwidget/actions/thumbnailAction.class.php(500): myEntryUtils::resizeEntryImage(Object(entry), 0, 0, 0, 1, 'ffffff', NULL, 0, 0, 0, 0, 0, 4.9, '-1', '-1', '/opt/kaltura/we...', NULL, NULL, Object(kThumbnailParameters), 'png', Object(FileSync), -1, -1)
#3 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(905): thumbnailAction->execute()
#4 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(1006): sfExecutionFilter->execute(Object(sfFilterChain))
#5 /opt/kaltura/app/vendor/symfony/filter/sfFlashFilter.class.php(50): sfFilterChain->execute()
#6 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(1006): sfFlashFilter->execute(Object(sfFilterChain))
#7 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(830): sfFilterChain->execute()
#8 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(1006): sfCommonFilter->execute(Object(sfFilterChain))
#9 /opt/kaltura/app/alpha/apps/kaltura/lib/filter/myHealthCheckAndSecurityFilter.class.php(65): sfFilterChain->execute()
#10 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(1006): myHealthCheckAndSecurityFilter->execute(Object(sfFilterChain))
#11 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(974): sfFilterChain->execute()
#12 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(1006): sfRenderingFilter->execute(Object(sfFilterChain))
#13 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(576): sfFilterChain->execute()
#14 /opt/kaltura/app/cache/alpha/kaltura/prod/config/config_core_compile.yml.php(2228): sfController->forward('extwidget', 'thumbnail')
#15 /opt/kaltura/app/alpha/bootstrap.php(31): sfFrontWebController->dispatch()
#16 /opt/kaltura/app/alpha/web/index.php(264): require_once('/opt/kaltura/ap...')
#17 {main}
2023-08-30 12:57:47 [0.000167] [92.117.221.74] [1402175021] [59] [PS2] [KExternalErrors::terminateDispatch] DEBUG: Dispatch took - 0.047521114349365 seconds, memory: 2097152

**Linux distribution name and version:**
Ubuntu 16.04.7 LTS

**Are you using the RPM or deb packages?**
- [ ] RPM
- [X ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
+++-==============-============-============-=================================
ii  kaltura-base   16.14.0-1+b2 all          Kaltura Open Source Video Platfor
ii  kaltura-batch  16.14.0-1    all          Kaltura Open Source Video Platfor
ii  kaltura-clipap 1.3-1+b2     all          Kaltura Video Presentations Manag
ii  kaltura-db     15.10.0-1+b1 all          Kaltura Open Source Video Platfor
ii  kaltura-dwh    15.1.0-1+b2  amd64        Kaltura Open Source Video Platfor
ii  kaltura-elasti 1.0.0-1+b11  all          Kaltura Open Source Video Platfor
ii  kaltura-ffmpeg 4.0.2-3      amd64
ii  kaltura-ffmpeg 2.1.3-1      amd64
ii  kaltura-flexwr 1.2-1+b1     all          Kaltura Video Presentations Manag
ii  kaltura-front  16.14.0-1    all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 0.3          all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 2.2.3-1      all          Kaltura Open Source Video Platfor
ii  kaltura-html5- 3.8.0-1      all          Kaltura Open Source Video Platfor
ii  kaltura-html5l 2.85-1+b3    all          Kaltura Open Source Video Platfor
ii  kaltura-html5l 1.2.1-1      all          Kaltura Open Source Video Platfor
ii  kaltura-kclip  1.1.2.1-1    all          Kaltura Video Presentations Manag
ii  kaltura-kcw    2.2.4-1+b6   all          Kalture Contribution Wizard
ii  kaltura-kdp    2.7.0-1+b1   all          Kaltura Dynamic Player
ii  kaltura-kdp3   3.9.9-1+b4   amd64        Kaltura Dynamic Player
ii  kaltura-kdp3wr 37-1+b3      all          KDP3 Wrapper
ii  kaltura-kdpwra 11-1+b2      all          KDP Wrapper
ii  kaltura-kmc    5.43.13-11+b all          Kaltura Management Console
ii  kaltura-kmcng  5.19-3+reall all          Kaltura Management Console
ii  kaltura-krecor 1.7-1+b1     all          Kaltura kRecord - used for record
ii  kaltura-kuploa 1.2.16-1+b2  all          Kaltura kupload widget
un  kaltura-libapa <keine>      <keine>      (keine Beschreibung vorhanden)
ii  kaltura-nginx  1.17.10-1    amd64        Nginx web/proxy server - for Kalt
ii  kaltura-pentah 4.2.1+b2     amd64        Pentaho Open Source Data Integrat
un  kaltura-php7-a <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-c <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-c <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-g <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-g <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-m <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-m <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-s <keine>      <keine>      (keine Beschreibung vorhanden)
un  kaltura-php7-x <keine>      <keine>      (keine Beschreibung vorhanden)
ii  kaltura-playki 1.2.0-1+b7   all          Kaltura Open Source Video Platfor
ii  kaltura-postin 1.0.33-3+b13 all          Kaltura Open Source Video Platfor
ii  kaltura-sphinx 2.2.1-4+b4   amd64        Sphinx full-text search server -
ii  kaltura-widget 14.1.0-1     all          Kaltura Open Source Video Platfor

```

**Is this an all in one instance [single server] or a cluster?**
- [X ] All in one
- [ ] Cluster

We know we are using an older version, but upgrading it on the production environment isn't that easy at this time. Would an upgrade even resolve this issue or is there anything else we can do?

**Comment by enkosoftware** [comment]
@GElkayam anything we can do?

**Comment by atmike** [comment]
@matsuu @cstigler  @stuartf  @shojikajita  
Hello can you us with this Problem?
it is very urgent 
Regards Michael

**Comment by GElkayam** [comment]
@enkosoftware , I stumbled upon this issue by mistake, and noticed you have tagged me.
The issue is that the thumbnail was still processing, so the system blocks multiple calls to generate the thumbnail to avoid overloading the system.
https://github.com/kaltura/server/blob/Propus-16.14.0/alpha/apps/kaltura/lib/myEntryUtils.class.php#L852
