### ISSUE TITLE
10.4. Playlists Tab Internal Server Error

### ISSUE THREAD

**Issue by himbeere** [kaltura/server#2266]
Hello.

When hitting the playlists button i get a flash window "internal server error". Kaltlog says:

```
#13 {main}
2015-02-21 11:52:58 [0.000461] [92.195.174.160] [1383480167] [API]     [KalturaFrontController->getExceptionObject] CRIT: exception 'kFileSyncException' with message 'Cannot find file on local disk [] for file sync [672]' in /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php:76
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(176): kFileSyncUtils::getContentsByFileSync(Object(FileSync), true, true, false)
--
2015-02-21 11:53:37 [0.000090] [92.195.174.160] [298061194] [API] [kFileSyncUtils::getContentsByFileSync] INFO: file was not found locally []
2015-02-21 11:53:37 [0.000313] [92.195.174.160] [298061194] [API] [kCoreException->__construct] ERR: exception 'kFileSyncException' with message 'Cannot find file on local disk [] for file sync [672]' in /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php:76
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(176): kFileSyncUtils::getContentsByFileSync(Object(FileSync), true, true, false)
--
#13 {main}
2015-02-21 11:53:37 [0.000479] [92.195.174.160] [298061194] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kFileSyncException' with message 'Cannot find file on local disk [] for file sync [672]' in /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php:76
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(176): kFileSyncUtils::getContentsByFileSync(Object(FileSync), true, true, false)
```

**Comment by tan-tan-kanarek** [comment]
Hi,
There are many different reasons that may cause different files in the system to be missing, for example, disc is full, server cleanup misconfigured or erroneous server installation.
I can't tell from your logs if a specific playlist caused it, or a specific ui-conf.
Having the full log could give us more info.
My first guess would be template playlists that were not ingested properly.
To solve it, use mysql to find all active playlist of the publisher and delete them one by one using the testme console.

**Comment by himbeere** [comment]
Hello.

Thanks for your answer. Actually it's a complete empty installation. There is no playlist at all at the moment. And i am not able to create one because of the error. Any other ideas? Thanks for your help again.

cheers.
t.

**Comment by tan-tan-kanarek** [comment]
In empty installation there is already template playlists.
I suggest that using HTTP sniffer you'll find what exact API call returned the internal server error and I'll be able to direct you what should be searched in the log.
Post data and response headers can help me to direct you.

**Comment by himbeere** [comment]
Hola.

okay. so i have to do a tcpdump. thanks so far.

cheers
t.

**Comment by jessp01** [comment]
Closing this issue. If you have additional questions or need more help, please submit to forum.kaltura.org.
