### ISSUE TITLE
video conversion failure

### ISSUE THREAD

**Issue by Eberx** [kaltura/server#2294]
I cannot convert video. I can upload video through KMC upload. But the status of media changed to converting then error occurred.

This is failed task information

1. Failed to extract media info: /opt/kaltura/web/content/entry/data/0/1/0_mu0uzmhc_0_nulk5lc0_12.avi	
2. engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]

This is kaltlog error

PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'couldn't connect to host' in /opt/kaltura/app/batch/client/KalturaClientBase.php:357
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaPlugins/KalturaContentDistributionClientPlugin.php(2425): KalturaClientBase->doQueue()
--
  thrown in /opt/kaltura/app/batch/client/KalturaClientBase.php on line 357
PHP Fatal error:  Uncaught exception 'KalturaClientException' with message 'SSL connect error' in /opt/kaltura/app/batch/client/KalturaClientBase.php:357
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClient.php(3995): KalturaClientBase->doQueue()

kaltlog when video conversion starts

2015-03-04 08:59:26 [1686251678] [KBaseMediaParser->getRawMediaInfo] DEBUG: Executing '/usr/bin/mediainfo "/opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi"'
2015-03-04 08:59:26 [1686251678] [KAsyncExtractMedia->extract] ERR: exception 'Exception' with message 'Failed to parse media using KMediaInfoMediaParser' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/ExtractMedia/KAsyncExtractMedia.class.php(97): KalturaLog::err('Failed to parse...')
--

4 {main}
2015-03-04 08:59:26 [1686251678] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to extract media info: /opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to extra...')
--
[line:protected] => 41
[trace:Exception:private] => Array
(
--
2015-03-04 09:00:31 [1364303040] [KBaseMediaParser->getRawMediaInfo] DEBUG: Executing '/usr/bin/mediainfo "/opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi"'
2015-03-04 09:00:31 [1364303040] [KAsyncExtractMedia->extract] ERR: exception 'Exception' with message 'Failed to parse media using KMediaInfoMediaParser' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/ExtractMedia/KAsyncExtractMedia.class.php(97): KalturaLog::err('Failed to parse...')
--

4 {main}
2015-03-04 09:00:31 [1364303040] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to extract media info: /opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to extra...')
--
[line:protected] => 41
[trace:Exception:private] => Array
(
--
2015-03-04 09:01:34 [154904534] [KBaseMediaParser->getRawMediaInfo] DEBUG: Executing '/usr/bin/mediainfo "/opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi"'
2015-03-04 09:01:34 [154904534] [KAsyncExtractMedia->extract] ERR: exception 'Exception' with message 'Failed to parse media using KMediaInfoMediaParser' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/ExtractMedia/KAsyncExtractMedia.class.php(97): KalturaLog::err('Failed to parse...')
--

4 {main}
2015-03-04 09:01:34 [154904534] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to extract media info: /opt/kaltura/web/content/entry/data/0/1/0_4v0t5qfs_0_blj5lmdk_12.avi' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to extra...')
--
2015-03-04 09:01:50 [1992634275] [KalturaClientBase->doQueue] NOTICE: execution time for [https://HOSTNAME:443/api_v3/index.php?service=batch&action=logConversion]: [0.12168908119202]
2015-03-04 09:01:50 [1992634275] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('engine [KOperat...')
--
2015-03-04 09:01:51 [0.000640] [103.48.116.77] [1932565477] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.0004279613494873 seconds
2015-03-04 09:01:51 [0.000945] [103.48.116.77] [1932565477] [API] [kFileSyncUtils::moveFromFile] ERR: exception 'Exception' with message 'file already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(443): KalturaLog::err('file already ex...')
--

14 {main}
2015-03-04 09:01:51 [0.000603] [103.48.116.77] [1932565477] [API] [kFlowHelper::handleConvertFailed] ERR: exception 'Exception' with message 'Saving conversion log: key [object_type:[4], object_id:[0_zi16fz57], version:[2], object_sub_type[2], partner_id[102]] already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kFlowHelper.php(1113): KalturaLog::err('Saving conversi...')
--
2015-03-04 09:01:52 [553130920] [KalturaClientBase->doQueue] NOTICE: execution time for [https://HOSTNAME:443/api_v3/index.php?service=batch&action=logConversion]: [0.15160202980042]
2015-03-04 09:01:52 [553130920] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('engine [KOperat...')
--
2015-03-04 09:01:53 [0.001675] [103.48.116.77] [1904444185] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.0013439655303955 seconds
2015-03-04 09:01:53 [0.000452] [103.48.116.77] [1904444185] [API] [kFileSyncUtils::moveFromFile] ERR: exception 'Exception' with message 'file already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(443): KalturaLog::err('file already ex...')
--

14 {main}
2015-03-04 09:01:53 [0.000371] [103.48.116.77] [1904444185] [API] [kFlowHelper::handleConvertFailed] ERR: exception 'Exception' with message 'Saving conversion log: key [object_type:[4], object_id:[0_zi16fz57], version:[12], object_sub_type[2], partner_id[102]] already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kFlowHelper.php(1113): KalturaLog::err('Saving conversi...')
--
2015-03-04 09:01:54 [1564386862] [KalturaClientBase->doQueue] NOTICE: execution time for [https://HOSTNAME:443/api_v3/index.php?service=batch&action=logConversion]: [0.16872382164001]
2015-03-04 09:01:55 [1564386862] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('engine [KOperat...')
--
==> /opt/kaltura/log/kaltura_api_v3.log <==
2015-03-04 09:01:55 [0.000466] [103.48.116.77] [164062551] [API] [kFileSyncUtils::moveFromFile] ERR: exception 'Exception' with message 'file already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(443): KalturaLog::err('file already ex...')
--
==> /opt/kaltura/log/kaltura_api_v3.log <==
2015-03-04 09:01:55 [0.000510] [103.48.116.77] [164062551] [API] [kFlowHelper::handleConvertFailed] ERR: exception 'Exception' with message 'Saving conversion log: key [object_type:[4], object_id:[0_zi16fz57], version:[22], object_sub_type[2], partner_id[102]] already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kFlowHelper.php(1113): KalturaLog::err('Saving conversi...')
--
2015-03-04 09:01:55 [0.000171] [103.48.116.77] [164062551] [API] [kJobsManager::getNextConversionEngine] NOTICE: Last used conversion engine is [3]
2015-03-04 09:01:55 [0.000296] [103.48.116.77] [164062551] [API] [kJobsManager::getNextConversionEngine] ERR: exception 'Exception' with message 'There is no other conversion engine to use' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kJobsManager.php(679): KalturaLog::err('There is no oth...')
--
2015-03-04 09:01:56 [660607578] [KalturaClientBase->doQueue] NOTICE: execution time for [https://HOSTNAME:443/api_v3/index.php?service=batch&action=logConversion]: [0.10291600227356]
2015-03-04 09:01:56 [660607578] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('engine [KOperat...')
--
2015-03-04 09:01:57 [0.000557] [103.48.116.77] [1963709757] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00037503242492676 seconds
2015-03-04 09:01:57 [0.000392] [103.48.116.77] [1963709757] [API] [kFileSyncUtils::moveFromFile] ERR: exception 'Exception' with message 'file already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(443): KalturaLog::err('file already ex...')
--

14 {main}
2015-03-04 09:01:57 [0.000303] [103.48.116.77] [1963709757] [API] [kFlowHelper::handleConvertFailed] ERR: exception 'Exception' with message 'Saving conversion log: key [object_type:[4], object_id:[0_cstbf8g7], version:[2], object_sub_type[2], partner_id[102]] already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kFlowHelper.php(1113): KalturaLog::err('Saving conversi...')
--
2015-03-04 09:01:59 [2023150337] [KalturaClientBase->doQueue] NOTICE: execution time for [https://HOSTNAME:443/api_v3/index.php?service=batch&action=logConversion]: [0.16020512580872]
2015-03-04 09:01:59 [2023150337] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'engine [KOperationEngineOldVersionWrapper] converted failed: return value: [1]' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('engine [KOperat...')
--
2015-03-04 09:01:59 [0.000698] [103.48.116.77] [1212468821] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00050878524780273 seconds
2015-03-04 09:01:59 [0.000397] [103.48.116.77] [1212468821] [API] [kFileSyncUtils::moveFromFile] ERR: exception 'Exception' with message 'file already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/storage/kFileSyncUtils.class.php(443): KalturaLog::err('file already ex...')
--

14 {main}
2015-03-04 09:01:59 [0.000295] [103.48.116.77] [1212468821] [API] [kFlowHelper::handleConvertFailed] ERR: exception 'Exception' with message 'Saving conversion log: key [object_type:[4], object_id:[0_cstbf8g7], version:[12], object_sub_type[2], partner_id[102]] already exists' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kFlowHelper.php(1113): KalturaLog::err('Saving conversi...')
--
2015-03-04 09:01:59 [0.000170] [103.48.116.77] [1212468821] [API] [kJobsManager::getNextConversionEngine] NOTICE: Last used conversion engine is [99]
2015-03-04 09:01:59 [0.000330] [103.48.116.77] [1212468821] [API] [kJobsManager::getNextConversionEngine] ERR: exception 'Exception' with message 'There is no other conversion engine to use' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/alpha/apps/kaltura/lib/batch2/kJobsManager.php(679): KalturaLog::err('There is no oth...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_cstbf8g7_2.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:06 [1497077560] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_cstbf8g7_12.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:08 [1285947283] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_cstbf8g7_2.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:10 [361676918] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_2.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:13 [1129622257] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_22.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:15 [1486980699] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_22.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:17 [456898805] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_cstbf8g7_12.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:19 [1251584918] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_2.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:21 [2031774049] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_12.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:23 [1218459118] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')
--
==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.err.log <==
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_12.conv.log): Permission denied in /opt/kaltura/app/batch/batches/DeleteFile/KAsyncDeleteFile.class.php on line 25

==> /opt/kaltura/log/batch/deletefile-0-2015-03-04.log <==
2015-03-04 09:02:25 [1964220041] [KJobHandlerWorker->closeJob] ERR: exception 'Exception' with message 'Failed to delete file from disk' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:

0 /opt/kaltura/app/batch/batches/KJobHandlerWorker.class.php(336): KalturaLog::err('Failed to delet...')

**Comment by jessp01** [comment]
PHP Warning: unlink(/opt/kaltura/web//content/entry/data/0/1/0_4v0t5qfs_0_zi16fz57_12.conv.log): Permission denied
And there are a lot of these. I suspect you have bad permissions on your /opt/kaltura/web/ subdirs.
Look at http://forum.kaltura.org/t/conversion-failed/1827/9
fix them accordingly and the post an issue in the forum if you are still having a problem.
