### ISSUE TITLE
cannot login to KMC console

### ISSUE THREAD

**Issue by samerk1** [kaltura/server#2742]
I have a fresh copy of RHEL7, and I have installed kaltura using below link as Non-SSL install option. 
https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md

When I run the command "/opt/kaltura/bin/kaltura-base-config.sh" then it ask for all the details along with MySQL DB user name and password.
From the command line i can connect to the DB with kaltura username.
KMC opens fine, however i am not able to login with the KMC admin user ADMIN_CONSOLE_ADMIN_MAIL and passwd (the ones in /tmp/kaltura_24_06_14_50.ans)

sanity check fails at the end with:
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.053644223]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.021714288]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.025248215]
[Get KMC SWFs] [FAILED, RC: 255] - [.265364048]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.162057670]
[check_kmc_index_page] [FAILED, RC: 1] - [.159813091]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.162218339]
[check_studio_index_page] [FAILED, RC: 1] - [.161908233]
[check_clipapp_index_page] [FAILED, RC: 1] - [1.201716778]
[Create Partner] [FAILED, RC: 255] - [.251816319]
Partner creation failed. I will skip all tests that require it.
[Red5 file upload] [FAILED, RC: 3] - [.012004298]

And when i login from web i get the following error in kaltlog :'User was not found'

2015-06-24 15:20:19 [0.000324] [192.168.1.114] [1463869856] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.0002131462097168 seconds
2015-06-24 15:20:19 [0.000402] [192.168.1.114] [1463869856] [API] [kCoreException->__construct] ERR: exception 'kUserException' in /opt/kaltura/app/alpha/lib/model/UserLoginDataPeer.php:352
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseUserService.php(178): UserLoginDataPeer::userLoginByEmail('samerk@aub.edu....', 'qaz@1234', 0)
--
#8 {main}
2015-06-24 15:20:19 [0.000580] [192.168.1.114] [1463869856] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'User was not found' in /opt/kaltura/app/api_v3/lib/KalturaBaseUserService.php:187
Stack trace:
#0 /opt/kaltura/app/api_v3/services/UserService.php(360): KalturaBaseUserService->loginImpl(NULL, 'samerk@aub.edu....', 'qaz@1234', 0, 86400, 'disableentitlem...')
--
2015-06-24 15:20:19 [0.000694] [192.168.1.114] [1463869856] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.0005497932434082 seconds
2015-06-24 15:20:19 [0.000233] [192.168.1.114] [1463869856] [API] [kPermissionManager::isActionPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/kPermissionManager.php(807): KalturaLog::err('Action is not p...')
--
#9 {main}
2015-06-24 15:20:19 [0.000151] [192.168.1.114] [1463869856] [API] [KalturaBaseService->isPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseService.php(190): KalturaLog::err('Action is not p...')
--
#8 {main}
2015-06-24 15:20:19 [0.000128] [192.168.1.114] [1463869856] [API] [KalturaBaseService->isPermitted] ERR: exception 'Exception' with message 'Kaltura network is not allowed' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseService.php(199): KalturaLog::err('Kaltura network...')
--
#8 {main}
2015-06-24 15:20:19 [0.000176] [192.168.1.114] [1463869856] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'The access to service [user->getByLoginId] is forbidden' in /opt/kaltura/app/api_v3/lib/KalturaBaseService.php:135
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseUserService.php(30): KalturaBaseService->initService('user', 'user', 'getByLoginId')
--
2015-06-24 15:20:19 [0.000601] [192.168.1.114] [1463869856] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00047588348388672 seconds
2015-06-24 15:20:19 [0.000204] [192.168.1.114] [1463869856] [API] [kPermissionManager::isActionPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/kPermissionManager.php(807): KalturaLog::err('Action is not p...')
--
#9 {main}
2015-06-24 15:20:19 [0.000137] [192.168.1.114] [1463869856] [API] [KalturaBaseService->isPermitted] ERR: exception 'Exception' with message 'Action is not permitted' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseService.php(190): KalturaLog::err('Action is not p...')
--
#8 {main}
2015-06-24 15:20:19 [0.000146] [192.168.1.114] [1463869856] [API] [KalturaBaseService->isPermitted] ERR: exception 'Exception' with message 'Kaltura network is not allowed' in /opt/kaltura/app/infra/log/KalturaLog.php:82
Stack trace:
#0 /opt/kaltura/app/api_v3/lib/KalturaBaseService.php(199): KalturaLog::err('Kaltura network...')
--
#8 {main}
2015-06-24 15:20:19 [0.000212] [192.168.1.114] [1463869856] [API] [KalturaFrontController->getExceptionObject] ERR: exception 'KalturaAPIException' with message 'The access to service [permission->list] is forbidden' in /opt/kaltura/app/api_v3/lib/KalturaBaseService.php:135
Stack trace:
#0 /opt/kaltura/app/api_v3/services/PermissionService.php(13): KalturaBaseService->initService('permission', 'permission', 'list')

I have the followinf installed

[root@lego tmp]# rpm -qa | grep kaltura
kaltura-lame-3.99.5-3.x86_64
kaltura-kdpwrapper-v11.0-1.noarch
kaltura-dwh-9.4.0-2.noarch
kaltura-red5-1.0.3-3.x86_64
kaltura-batch-10.13.0-1.noarch
kaltura-libfaac-1.28-1.x86_64
kaltura-libass-0.9.11-2.x86_64
kaltura-ffmpeg-aux-0.6-2.x86_64
kaltura-krecord-1.0.0-1.noarch
kaltura-kdp3-v3.9.9-2.noarch
kaltura-release-10.13.0-1.noarch
kaltura-libmcrypt-2.5.8-2.x86_64
kaltura-fdk-aac-0.1.3-1.x86_64
kaltura-segmenter-1.0-1.x86_64
kaltura-kdp3wrapper-v37.0-1.noarch
kaltura-flexwrapper-v1.2-1.noarch
kaltura-html5lib-v2.31-2.noarch
kaltura-x264-0.140-2.20140104.x86_64
kaltura-sshpass-1.05-1.x86_64
kaltura-ffmpeg-2.1.3-2.x86_64
kaltura-kupload-1.0.0-1.noarch
kaltura-kvpm-v1.0.6-1.noarch
kaltura-kcw-1.0.0-6.noarch
kaltura-widgets-1.0.0-8.noarch
kaltura-sphinx-2.2.1-16.x86_64
kaltura-pentaho-4.2.1-1.x86_64
kaltura-mencoder-3.4.6-9.x86_64
kaltura-html5-studio-v1.9.8-1.noarch
kaltura-base-10.13.0-7.noarch
kaltura-server-10.13.0-1.noarch
kaltura-a52dec-0.7.4-11.x86_64
kaltura-kclip-v1.1.2.1-2.noarch
kaltura-kdp-v2.7.0-1.noarch
kaltura-kmc-v5.39.3-2.noarch
kaltura-libopencore-amr-0.1.3-1.x86_64
kaltura-monit-5.6-15.x86_64
kaltura-clipapp-1.3-2.noarch
kaltura-nginx-1.8.0-1.x86_64
kaltura-front-10.13.0-1.noarch
kaltura-postinst-1.0.26-6.noarch
[root@lego tmp]#

**Comment by jessp01** [comment]
Hello,

When doing an all in one install, running kaltura-base-config.sh is not 
enough, you need to run kaltura-config-all.sh.

If there are any errors while deploying, they of course need to be fixed.
after running it, if there are still issues, post on forum.kaltura.org and 
include the full install log.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
virtualconnect.kaltura.com
