### ISSUE TITLE
Internal database error after log into KMC (only on clicking Dashboard page and analytic page)

### ISSUE THREAD

**Issue by vikchallenge** [kaltura/server#3289]
Hello All

I am using kaltura cluster 10/.19 CE edtiton 
and my mysql version is 
mysql-libs-5.1.73-5.el6_6.x86_64
mysql-5.1.73-5.el6_6.x86_64
php-mysql-5.3.3-46.el6_6.x86_64

and i am facing following issue according kaltlog

--
2015-10-07 21:20:58 [0.000069] [1671756171] [50] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2015-10-07 21:20:58 [0.001021] [1671756171] [51] [BATCH] [KAsyncDropFolderWatcher->setDropFolderError] ERR: exception 'Exception' with message 'Error with folder id [3] - Drop folder path not valid [/opt/kaltura/web/content/TestDropFolder]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(117): KalturaLog::err('Error with fold...')
--
2015-10-07 21:21:59 [0.000071] [1388455543] [50] [BATCH] [kFileTransferMgr->fileExists] DEBUG: File does not exist
2015-10-07 21:21:59 [0.000998] [1388455543] [51] [BATCH] [KAsyncDropFolderWatcher->setDropFolderError] ERR: exception 'Exception' with message 'Error with folder id [3] - Drop folder path not valid [/opt/kaltura/web/content/TestDropFolder]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/plugins/drop_folder/batch/DropFolderWatcher/KAsyncDropFolderWatcher.class.php(117): KalturaLog::err('Error with fold...')
--
2015-10-07 21:22:53 [0.000216] [122.184.129.18] [304805033] [29] [API] [KalturaFrontController->errorHandler] WARN: /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php line 1325 - mysqli_error() expects parameter 1 to be mysqli, boolean given
2015-10-07 21:22:53 [0.000129] [122.184.129.18] [304805033] [30] [API] [kCoreException->__construct] ERR: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('?SELECT??DATE(D...')
--
2015-10-07 21:22:53 [0.000144] [122.184.129.18] [304805033] [31] [API] [myReportsMgr::executeQueryByType] NOTICE: Can't use foo : 
2015-10-07 21:22:53 [0.000248] [122.184.129.18] [304805033] [32] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('?SELECT??DATE(D...')
--
2015-10-07 21:22:53 [0.000131] [122.184.129.18] [304805033] [45] [API] [KalturaFrontController->errorHandler] WARN: /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php line 1325 - mysqli_error() expects parameter 1 to be mysqli, boolean given
2015-10-07 21:22:53 [0.000122] [122.184.129.18] [304805033] [46] [API] [kCoreException->__construct] ERR: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('# return count_...')
--
2015-10-07 21:22:53 [0.000123] [122.184.129.18] [304805033] [47] [API] [myReportsMgr::executeQueryByType] NOTICE: Can't use foo : 
2015-10-07 21:22:53 [0.000148] [122.184.129.18] [304805033] [48] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('# return count_...')

and i think my batch also not working it failed every time........
[root@batch ~]# service kaltura-batch restart
Shutting down:[FAILED]
Service Batch not running
Starting:[FAILED]
Service batch isn't running but stale lock file exists
Removing stale lock file at /opt/kaltura/log/batch/batch.pid
/usr/bin/php KGenericBatchMgr.class.php /usr/bin/php /opt/kaltura/app/configurations/batch >> /opt/kaltura/log/kaltura_batch.log 2>&1 &
[       OK      ]

please help

**Comment by kaltura-hooks** [comment]
Hi @vikchallenge,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello,

The first issue:
```
2015-10-07 21:20:58 [0.001021] [1671756171] [51] [BATCH] [KAsyncDropFolderWatcher->setDropFolderError] ERR: exception 'Exception' with message 'Error with folder id [3] - Drop folder path not valid [/opt/kaltura/web/content/TestDropFolder]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
```

Stems from the fact you created a drop folder, indicating the location /opt/kaltura/web/content/TestDropFolder but, did not create this directory on the file system or else, did not provide proper permissions so that the batch user [kaltura] can access it.

The second issue:
```
2015-10-07 21:22:53 [0.000123] [122.184.129.18] [304805033] [47] [API] [myReportsMgr::executeQueryByType] NOTICE: Can't use foo :
2015-10-07 21:22:53 [0.000148] [122.184.129.18] [304805033] [48] [API] [KalturaFrontController->getExceptionObject] CRIT: exception 'kCoreException' with message 'Can't use foo : ' in /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php:1325
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/reports/myReportsMgr.class.php(879): myReportsMgr::executeQuery('# return count_...')```

means that the analytics DB cannot be reached.
Open /opt/kaltura/app/configurations/local.ini and look under the reports_db_config section, you should see something like:
```
[reports_db_config]
host = mysql_host_name
user = etl
port = 3306
password = somepasswd
db_name = kalturadw
```
try to reach it using the mysql CLI client like so:
\# mysql -h mysql_host_name -uetl -psomepasswd kalturadw

It will fail and then we need to understand why.. make sure this DB actually exists, it is possible you had some issue when running kaltura-dwh-config.sh which cause the needed Analytics DB not to be created.

If your DWH DBs are corrupted, take a look at:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.21.0/doc/kaltura-packages-faq.md#analytics-issues
There is an explanation on how to drop them completely and recreate them.

As for the batch daemon, first:
\# /etc/init.d/kaltura-batch stop
\# ps fax|grep kaltura|grep php
make sure you have no loose batch children and if you do, kill then.
\# /etc/init.d/kaltura-batch start
and look for errors in /opt/kaltura/log/kaltura_batch.log that may cause the batch daemon to crush.

**Comment by jessp01** [comment]
I am closing this issue cause it does not appear to be a general bug but rather an issue specific to your deployment, in which case, we prefer it to be discussed on the forum at forum.kaltura.org.
If you have additional questions post checking the above, please post there and reference this github issue.

Thanks,
