### ISSUE TITLE
Video can't play after configuring the AWS Cloudfront

### ISSUE THREAD

**Issue by tarungupta01** [kaltura/server#9662]
- [ ] I've read the [guidelines for Contributing to Kaltura Projects](https://github.com/kaltura/platform-install-packages/blob/master/CONTRIBUTING.md)
- [ ] This is not a support re
![error](https://user-images.githubusercontent.com/69425409/89733887-30ec2580-da76-11ea-92a1-98cf26fe93d4.PNG)
quest or question that should be posted on the [Kaltura forum](https://forum.kaltura.org) or submitted to the support team in the form of a ticket 

## Bug report
**Please provide a detailed description of the issue and the steps to reproduce:**

## Kaltura ENV
*Please fill out this section if you are hosting the Kaltura platform on your own servers [as opposed to using Kaltura SaaS]. In the event of SaaS, the below should be deleted.*

**Relevant errors from /opt/kaltura/log/kaltura_api_v3.log, /opt/kaltura/log/kaltura_apache_errors*log and /opt/kaltura/log/kaltura_prod.log:**

**Linux distribution name and version:**

**Are you using the RPM or deb packages?**
- [ ] RPM
- [ ] deb

**When using RPM, paste the output for:**
```
# rpm -qa "kaltura-*"
```

**For deb based systems:**
```
# dpkg -l "kaltura-*"
```

**Is this an all in one instance [single server] or a cluster?**
- [ ] All in one
- [ ] Cluster

**If applicable, please provide the MySQL version:**

**If you're having an issue with a specific media asset, please provide a link from which it can be downloaded/played:**

**Comment by tarungupta01** [comment]
I am following this documentation to set up the AWS Cloudfront as a CDN: https://www.oodlestechnologies.com/blogs/Using-Cloudfront-and-S3-in-Kaltura-Video-Platform/
After following the above steps, video can't play. getting the below error which is mentioned in the screenshot. Could you please help us with this?

![error](https://user-images.githubusercontent.com/69425409/89733932-89232780-da76-11ea-97d4-27990af6396a.PNG)

**Comment by tarungupta01** [comment]
@jessp01 could you please revert back on this? It's urgent issue we need to resolve this.

**Comment by tarungupta01** [comment]
I am getting the below error while running the video:

020-08-11 22:54:27 [0.000353] [117.214.153.139] [279008402] [68] [API] [KalturaStatement->execute] DEBUG: Sql took - 0.00029206275939941 seconds
2020-08-11 22:54:27 [0.000334] [117.214.153.139] [279008402] [69] [API] [DeliveryProfilePeer::getRemoteDeliveryByStorageId] ERR: Exception: Delivery ID can't be determined for storageId [2] ( PartnerId [102] ) and streamer type [ rtmp ] in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(456): KalturaLog::err('Delivery ID can...')
--
2020-08-11 22:54:41 [0.000330] [117.214.153.139] [2077114265] [33] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00026583671569824 seconds
2020-08-11 22:54:41 [0.000267] [117.214.153.139] [2077114265] [34] [PS2] [DeliveryProfilePeer::getRemoteDeliveryByStorageId] ERR: Exception: Delivery ID can't be determined for storageId [2] ( PartnerId [102] ) and streamer type [ applehttp ] in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(456): KalturaLog::err('Delivery ID can...')
--
#18 {main}
2020-08-11 22:54:41 [0.000082] [117.214.153.139] [2077114265] [35] [PS2] [KExternalErrors::dieError] ERR: Exception: exiting on error 25 - wrong query attributes, This format is unsupported in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(138): KalturaLog::err('exiting on erro...')
--
2020-08-11 22:54:42 [0.000326] [117.214.153.139] [1110805572] [33] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00026512145996094 seconds
2020-08-11 22:54:42 [0.000263] [117.214.153.139] [1110805572] [34] [PS2] [DeliveryProfilePeer::getRemoteDeliveryByStorageId] ERR: Exception: Delivery ID can't be determined for storageId [2] ( PartnerId [102] ) and streamer type [ applehttp ] in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(456): KalturaLog::err('Delivery ID can...')
--
#18 {main}
2020-08-11 22:54:42 [0.000080] [117.214.153.139] [1110805572] [35] [PS2] [KExternalErrors::dieError] ERR: Exception: exiting on error 25 - wrong query attributes, This format is unsupported in /opt/kaltura/app/infra/log/KalturaLog.php:88
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(138): KalturaLog::err('exiting on erro...')
